name: GUIManager
version: 10.0
main: com.gmail.bobason01.GUIManager
api-version: 1.13
author: crston
softdepend: [Vault]
commands:
  gui:
    description: Manages GUIs.
    usage: /gui <subcommand>
    aliases: [guim]
permissions:
  guimanager.*:
    description: Grants all permissions for GUIManager
    default: op
    children:
      guimanager.open: true
      guimanager.open.others: true
      guimanager.create: true
      guimanager.edit: true
      guimanager.delete: true
      guimanager.list: true
      guimanager.reload: true
      guimanager.import: true

  guimanager.open:
    description: Allows opening a GUI
    default: op

  guimanager.open.others:
    description: Allows opening a GUI for other players
    default: op

  guimanager.create:
    description: Allows creating a new GUI
    default: op

  guimanager.edit:
    description: Allows editing an existing GUI
    default: op

  guimanager.delete:
    description: Allows deleting a GUI
    default: op

  guimanager.list:
    description: Allows listing all GUIs
    default: op

  guimanager.reload:
    description: Allows reloading the plugin configuration
    default: op

  guimanager.import:
    description: Allows importing menus from other plugins (GUIPlus, DeluxeMenus)
    default: op